[Temp] Improvements
UBoys/DireWolf pull request #1
Opened 2018-11-11 17:16 UTC by novalain

Messing around with travis

2018-11-13 00:24 UTC, Carlbaum requested changes
Mostly fine - I'm just not that keen on the `#error` and removing the `#else`. See comments for where I mean

Don't really bother with these files as I have that major refactor coming in

2018-11-13 00:24 UTC, Carlbaum commented on src/vulkan/vulkansetup.cpp
> +#error "The DireWolf renderer is not yet setup for Vulkan on this platform. Supported operating systems are Linux and Windows";
Cool, never seen before.
This will however not compile for other platforms right? Do we want that? 
I had kind of designed the methods so they would return some fail state.. a false bool, nullptr, or in the latest iteration (which hasn't been checked in yet) VK_NULL_HANDLE. Which the user or DireWolf itself would then have to verify.

So if we want it as is, then I guess we'd have to wrap the includes within #ifdefs to ensure it'd compile?

Also, why would we wanna store these names in a constexpr/variable in the forst place? Seems like we still only use them in one place and we still have to use the `#if defines` there as well . Might as well just put it in there?

2018-11-13 00:24 UTC, Carlbaum commented on src/vulkan/vulkansetup.cpp
> +///////////////////////////////////////////////////////////////////////////////////////////////m/////
cool.. 'm' as in Michael? You sneaky, cheeky you!

2018-11-13 00:24 UTC, Carlbaum commented on src/vulkan/vulkansetup.cpp
>  #endif
This `#if` `#else` breaks the intended design. The fact that I reassigned `vulkan_library` to `nullptr` was just for clarity. 
Also, removing the `#elif` without specifying which platform is addressed in the `#else` seems scary. I guess it'd work because of the `#error`, but as I said above - I don't think that this is the behaviour we want?
Remember that I have a major refactor coming in though, so the structure in these files are completely remade.

2018-11-13 00:24 UTC, Carlbaum commented on src/vulkan/vulkansetup.cpp
> -        m_vulkanRTLFound = false;
No need to bother with the `vulkan_library` or `vulkanRTLFound` variables.. both are gone in the refactor

2018-11-13 00:24 UTC, Carlbaum commented on src/vulkan/vulkansetup.cpp
> +        std::cerr << "Could not get available instance extensions!" << std::endl;
Guess this should be placed in the method instead.. but that method has been refactored, and the fail where it would be placed is removed.

2018-11-13 10:43 UTC, novalain commented on src/vulkan/vulkansetup.cpp
> +#error "The DireWolf renderer is not yet setup for Vulkan on this platform. Supported operating systems are Linux and Windows";
Yeah no I don't think it makes any sense to even compile with VK_ENABLED if vulkan is not supported on the platform, what's the point of that? - better let the preprocessor catch that error? No need to wrap the headers or anything as we won't even include them if there's a non-supported platform. We should catch this error earlier though, and just assume APPLE/WIN/LINUX within vulkan imo

2018-11-13 10:43 UTC, novalain commented on src/vulkan/vulkansetup.cpp
> +///////////////////////////////////////////////////////////////////////////////////////////////m/////
lol

2018-11-13 10:44 UTC, novalain commented on src/vulkan/vulkansetup.cpp
>  #endif
Correct, as I said above I think we should assume win/apple/linux and otherwise catch the error earlier in the render engine

2018-11-13 10:45 UTC, novalain commented on src/vulkan/vulkansetup.cpp
> -        m_vulkanRTLFound = false;
Yeah no need to boolean if you can just check for nullptr on the library

2018-11-13 10:45 UTC, novalain commented on src/vulkan/vulkansetup.cpp
> +        std::cerr << "Could not get available instance extensions!" << std::endl;
Sounds good I was just debugging stuff

2018-11-13 15:15 UTC, novalain commented on src/vulkan/vulkansetup.cpp
>  #endif
Actually why not do it already in the CMake step? DIREWOLF_VULKAN_ENABLED should only be visible on OSX, Linux and Win no?

2018-11-13 22:10 UTC, Carlbaum commented on src/vulkan/vulkansetup.cpp
> +#error "The DireWolf renderer is not yet setup for Vulkan on this platform. Supported operating systems are Linux and Windows";
Yeah, I've thought about it and I agree - it shouldn't compile if the platform isn't supported.
Well the headers would be wrapped within VK_ENABLED though, right?

I'd say remove that entire `#if defined` scope with the `constexpr`s but add the `#error` to the existing `#else` in `initLibs`.
Or actually, better yet.. how about just adding this to the header:
```
#if !defined(_WIN32) || !defined(__linux)
#error  "The DireWolf renderer is not yet setup for Vulkan on this platform. blalbalballal.....";
#endif
```

2018-11-13 22:22 UTC, Carlbaum commented on src/vulkan/vulkansetup.cpp
>  #endif
I think it'd be nice if only the vulkan files (vulkan module?) keep track of what they support.. Then we don't need to bother with it from anywhere else. I think that could be a nice convention to follow, something like: "Features/classes which are only available on certain platforms should throw an `#error` in the top of the header file if compiled for a non-supported platform."
This will ensure that we encapsulate those types of headers/features/functionalities within a CMAKE set flag, like e.g. `DIREWOLF_VULKAN_ENABLED` (or whatever its called)

2018-11-14 07:49 UTC, novalain commented on src/vulkan/vulkansetup.cpp
> +#error "The DireWolf renderer is not yet setup for Vulkan on this platform. Supported operating systems are Linux and Windows";
Sounds good. I'll pass that task to your refactor

2018-11-14 07:50 UTC, novalain commented
Plx approve and handle the rest later on in the refactor

2018-11-14 17:09 UTC, Carlbaum approved these changes

2018-11-14 17:13 UTC, Carlbaum approved these changes
Adding a comment this time.. maybe itäll work now ;)

2018-11-14 17:29 UTC, merged